" General settings.
set nocompatible
set encoding=utf-8

" Add numbers to each line on the left-hand side.
set number relativenumber

syntax enable
set termguicolors

filetype on
filetype plugin on
set scrolloff=5
set noerrorbells
let g:netrw_special_syntax = 1

" vimwiki
let g:vimwiki_list = [{'syntax': 'markdown',
                      \'ext': 'md'}]

"let g:vimwiki_global_ext = 0

" Indentation settings.
" Sources: https://superuser.com/a/1104409
set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set backspace=eol,start,indent
set softtabstop=4
"set listchars=eol:⏎,tab:>-,trail:~,extends:>,precedes:<,space:_
"set list

" Search settings.
set hlsearch
set ignorecase
set incsearch
set smartcase

" REMAPS
let mapleader=" "
nnoremap <LEADER>e :Ex<CR>

" Reload .vimrc
nnoremap <leader>r :so $MYVIMRC<CR>

" NERDTree
nnoremap <LEADER>pv :NERDTreeToggle<CR>

" Plugin Manager: VimPlug
" Automatic installation
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
    "Plug 'tpope/vim-fugitive'
    "Plug 'jiangmiao/auto-pairs'
    Plug 'catppuccin/vim', { 'as': 'catppuccin' }
    Plug 'preservim/nerdtree'
    Plug 'vimwiki/vimwiki'
    Plug 'jceb/vim-orgmode'
    Plug 'tpope/vim-speeddating'
    "Plug 'dense-analysis/ale'
    "Plug 'OmniSharp/omnisharp-vim'
call plug#end()

"let g:ale_linters = { 'cs': ['OmniSharp'] }

" Colors
colorscheme catppuccin_mocha
set background=dark
